inference_gpu_ids = [0, 1, 2, 3]
trainer_gpu_ids = [4, 5, 6, 7]

seq_len = 16384
max_steps = 500

[ckpt]
interval = 20

[model]
name = "Qwen/Qwen2.5-14B-instruct"

[wandb]
project = "art-e-rl"
name = "art-e-rl-14b-2-5"
offline = true

[trainer]
dist_timeout_seconds = 3600

[trainer.optim]
lr = 2.4e-5
weight_decay = 0.0

[trainer.model]
optimization_dtype = "bfloat16"
reduce_dtype = "bfloat16"

[trainer.model.ac]
freq = 1

[trainer.model.lora]
rank = 8
dropout = 0.0
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

[orchestrator]
num_epochs = 10
batch_size = 256
rollouts_per_example = 16
oversampling_factor = 2.0

[orchestrator.sampling]
max_tokens = 2048
temperature = 0.7

[orchestrator.buffer]
online_difficulty_filtering = true

[[orchestrator.env]]
id = "art_e"
args = { max_turns = 10, judge_model = "gpt-5-mini", use_tool_count_reward = true, dataset_path = "data/art_e_vince_kaminski" }

[inference]
gpu_memory_utilization = 0.85

[inference.model]
enable_auto_tool_choice = true
tool_call_parser = "hermes"
enforce_eager = true
